DELIMITER = "|"

CMD_REGISTER = "REGISTER"
CMD_UPDATE_FILES = "UPDATE_FILES"
CMD_GET_PEERS = "GET_PEERS"
CMD_SEARCH_FILES = "SEARCH_FILES"
CMD_GET_ENDPOINT = "GET_ENDPOINT"
CMD_LOGOUT = "LOGOUT"

RES_REGISTER_OK = "REGISTER_OK"
RES_REGISTER_ERR = "REGISTER_ERR"
RES_PEER_LIST = "PEER_LIST"
RES_SEARCH_RESULTS = "SEARCH_RESULTS"
RES_ENDPOINT = "ENDPOINT"
RES_ERROR = "ERROR"

P2P_CMD_CHAT = "P2P_CHAT"
P2P_CMD_FILE_REQ = "P2P_FILE_REQ"
P2P_RES_FILE_OK = "P2P_FILE_OK"
P2P_RES_FILE_ERR = "P2P_FILE_ERR"


def build_message(*tokens):
    return DELIMITER.join("" if token is None else str(token) for token in tokens)
